version: '3.8'
services:
  api:
    restart: always
    build: ./mlops_bootcamp_team10/api
    ports:
      - "8000:8000"

  mlflow:
    restart: always
    build: ./mlflow
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: http://0.0.0.0:5000
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./models:/app/models  # Persist runs locally
    depends_on:
      - postgres
    command: mlflow server --backend-store-uri postgresql://mlflow_user:mlflow_password@postgres:5432/mlflow_db --default-artifact-root ${S3_REMOTE_URL}/mlflow/ --host 0.0.0.0

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"